#' Random List of FlyBase Gene IDs used to demonstrate the usage of the package.
#' @docType data
#'
#' @format list
#'
#' @examples
#' \dontrun{
#'  geneListExample
#' }
#'
"geneListExample"

#' Expression data example generated by getAllExpression() function saved in
#' an rda file.
#' @docType data
#'
#' @format dataframe
#'
#' @examples
#' \dontrun{
#'  expressionDataExample
#' }
#'
"expressionDataExample"
